#1.7.0
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'FSPlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '11.0'

  pod 'FSPlayer', :path => '../../'

end