#!/bin/sh
#
# 编译 Vulkan 着色器为 SPIR-V，并生成内嵌 C 头文件（*.spv.h）。
# 依赖 glslc（Android NDK 的 shader-tools 或 brew install shaderc）。
#
# 用法：cd 到本目录后执行 ./build-shaders.sh
#
set -e

cd "$(dirname "$0")"

GLSLC="${GLSLC:-glslc}"
if ! command -v "$GLSLC" >/dev/null 2>&1; then
    for cand in \
        "$ANDROID_NDK_HOME/shader-tools/darwin-x86_64/glslc" \
        "$HOME/Library/Android/sdk/ndk/27.3.13750724/shader-tools/darwin-x86_64/glslc"; do
        if [ -x "$cand" ]; then GLSLC="$cand"; break; fi
    done
fi
if ! command -v "$GLSLC" >/dev/null 2>&1 && [ ! -x "$GLSLC" ]; then
    echo "glslc not found; install via Android NDK shader-tools or: brew install shaderc" >&2
    exit 1
fi

# 输入文件 -> 生成符号前缀
for src in yuv.vert yuv.frag external.frag; do
    [ -f "$src" ] || continue
    "$GLSLC" -fshader-stage="${src##*.}" -o "$src.spv" "$src"
    sym=$(echo "$src" | tr './-' '___')
    {
        echo "/* Auto-generated by glslc + embed script. Do not edit. */"
        echo "static const unsigned char ${sym}_spv[] = {"
        od -An -v -tx1 "$src.spv" | awk '{for(i=1;i<=NF;i++){printf "0x%s, ", $i; n++; if(n%12==0) printf "\n"}} END{printf "\n"}'
        echo "};"
        echo "static const unsigned int ${sym}_spv_len = $(wc -c < "$src.spv" | tr -d ' ');"
    } > "$src.spv.h"
    echo "generated $src.spv.h"
done
